### ISSUE TITLE
tslint error: missing semicolon

### ISSUE THREAD

**Issue by keenwon** [prograhammer/vue-parser#2]
Hi. my tslint config enforces semicolons at the end of every statement.

![image](https://user-images.githubusercontent.com/5516478/34764034-1fb15964-f628-11e7-82fd-0e78b15be393.png)

![image](https://user-images.githubusercontent.com/5516478/34764042-289ad62c-f628-11e7-824d-3ca4d89e4441.png)

https://github.com/prograhammer/vue-parser/blob/master/src/index.ts#L27

**Comment by prograhammer** [comment]
Ah, right. I need to wrap that in a *tslint disable*. Will update it in the morning.

**Comment by prograhammer** [comment]
Fixed. :smile:
